version: '3.8'
networks:
    main:
        driver: bridge
    minio_net:
        driver: bridge

x-minio-common: &minio-common
    image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server --console-address ":9090" /mnt/data
    ports:
        - "9000:9000"
        - "9090:9090"
  # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
        test: ["CMD", "mc", "ready", "local"]
        interval: 5s
        timeout: 5s
        retries: 5
    

services:
    minio1:
        <<: *minio-common
        hostname: minio1
        volumes:
            - type: bind
              source:  data/minio/files
              target:  /mnt/data
            - type: bind
              source:  data/minio/config
              target:  /etc/config.env
        networks:
            - minio_net
    mongoDB:
        image: mongo:7.0.9
        container_name: 'dataDb'
        restart: unless-stopped
        ports:
            - ${DATA_DB_PORTS}
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DATA_DB_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DATA_DB_ROOT_PASS}
            MONGO_INITDB_DATABASE: application_database
        volumes:
            - ./data/mongo/mongodb_data_container:/data/db
        networks:
            - main

volumes:
    mongodb_data_container: